services:
  vsgkugelberg_db:
    image: mysql:8.0
    container_name: vsgkugelberg_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - vsgkugelberg_db_data:/var/lib/mysql

volumes:
  vsgkugelberg_db_data:
